---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        name: Check Yaml
      - id: end-of-file-fixer
        name: End of File Fixer
      - id: trailing-whitespace
        name: Trailing Whitespace

  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
        name: Docker Compose Check

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        name: Dockerfile Lint

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: Hadolint
        args:
          - --ignore=DL3059

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Black

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python Imports

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Shellcheck
        args: ["--color=always", "--exclude=SC1091"]

  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        name: Bashate
